### ISSUE TITLE
custom filter

### ISSUE THREAD

**Issue by Charvelau** [berndporr/iir1#10]
Dear Dr. Porr,

I have checked the custom class but havn't quite understand it, is it possible for it to realize the following three filters with it?

![equation](https://latex.codecogs.com/gif.latex?$$H_{2}=\frac{s&space;\tau_{1}^{2}}{\left(1&plus;s&space;\tau_{1}\right)^{2}}$$,&space;$$H_{3}=\frac{s}{\left(1&plus;s&space;\tau_{2}\right)^{2}\left(1&plus;\tau_{z}&space;s\right)}$$,&space;$$H_{1}=\frac{s&plus;2&space;s^{2}&space;\tau_{1}}{\left(1&plus;s&space;\tau_{1}\right)^{2}}-\frac{1-\tau_{z}&space;s}{\left(1&plus;s&space;\tau_{2}\right)^{2}}$$)

Thank you very much.
Sincerely,
Qingwei Liu, AIST, Japan

**Comment by Charvelau** [comment]
Dear Dr. Porr,

My understanding is I can realize H2 with TwoPole, https://github.com/berndporr/iir1/blob/dd0124bf0ce9eebe031b672425d0bc7dac1d87af/iir/Custom.h#L76,
what I am confused is about H3, and also SOSCascade for H1.

Thank you very much.
Sincerely,
Qingwei Liu, AIST, Japan

**Comment by berndporr** [comment]
These are all analogue filters in Laplace space. You need to transform that to z-space with the matched z transform or bilinar transform. Then factor them out as a chain of 2nd order digital filters (SOS). Then use the CustomSOS function to set the coefficients. I'd recommend you learn first how to translate an analogue filter into a digital one and do it with pen/paper or you can also use python functions to achieve that which can also generate the 2nd order chain. My teaching videos are here: https://www.youtube.com/user/DSPcourse/playlists?view=50&sort=dd&shelf_id=27
