### ISSUE TITLE
How to apply scale vales to custom filter?

### ISSUE THREAD

**Issue by ynnie** [berndporr/iir1#12]
Hi Dr. Porr,

I designed a filter in matlab, the filter can be exported as a SOS matrix and a vector of scale values, but I didn't find the function that accepts scale values in iir1, can you explain how to apply these scale values in iir1?

Thank you!
Yingnan

**Comment by berndporr** [comment]
Hi,

there are no "scale values" or "gain" as the 2nd order filers use all 6 coefficients of the biquad and the a0 is the inverse of the gain. The gain is internally calculated as b0 / a0. If you look at the SOS coefficients MATLAB generates you see that the 1st IIR coefficient a0 is always one (i.e. scale value is 1). If you set `a0 = 1/scale` that should do the trick if I understand MATLAB correctly but I haven't used MATLAB for 5 years! Either way the gain is calculated in Biquad.cpp: `gain = b0 / a0;`.

Best,
/Bernd

**Comment by ynnie** [comment]
Thank you! I'll test these solutions and post the results here!

**Comment by ynnie** [comment]
Thank you, you are right, I find the explanation in matlab's document.

The sos2tf function can transfer  SOS and gain to the numerator and denominator coefficients.

sos2tf 2nd-order sections to transfer function model conversion.
    [B,A] = sos2tf(SOS,G) returns the numerator and denominator
    coefficients B and A of the discrete-time linear system given
    by the gain G and the matrix SOS in second-order sections form.
 
    SOS is an L by 6 matrix which contains the coefficients of each
    second-order section in its rows:
        SOS = [ b01 b11 b21  1 a11 a21
                b02 b12 b22  1 a12 a22
                ...
                b0L b1L b2L  1 a1L a2L ]
    The system transfer function is the product of the second-order
    transfer functions of the sections times the gain G. If G is not
    specified, it defaults to 1. Each row of the SOS matrix describes
    a 2nd order transfer function as
        b0k +  b1k z^-1 +  b2k  z^-2
        ----------------------------
        1 +  a1k z^-1 +  a2k  z^-2
    where k is the row index.

**Comment by berndporr** [comment]
Excellent!
