### ISSUE TITLE
Changes in Cascade.h in order to compile on Clang

### ISSUE THREAD

**Issue by james34602** [berndporr/iir1#2]
Changes in Cascade.h in order to compile on Clang, google update android ndk compiler from GCC to Clang, add just one line can make the whole stuff work again.
https://github.com/james34602/JamesDSPManager/commit/7478665df6974479bfd47d99d5323ce8c209934b

**Comment by berndporr** [comment]
thanks. I've changed it. Won't harm anyway to have these public.
