### ISSUE TITLE
[REQ] Set license on GH

### ISSUE THREAD

**Issue by forart** [berndporr/iir1#26]
Hi there, this project is awesome !

Since we've collected it in our [HyMPS project list](https://github.com/forart/HyMPS) (in the [AudioLIBs section](https://github.com/forart/HyMPS/blob/main/AudioLIBs.md)), can you please set licensing terms on this git ?

Thanks in advance !

**Comment by berndporr** [comment]
Thanks! It's right here:
https://github.com/berndporr/iir1/blob/master/COPYING

**Comment by forart** [comment]
1st of all thanks for the fast reply.

Our "problem" is that not generates the label: https://flat.badgen.net/github/license/berndporr/iir1?label=LICENSE

![](https://flat.badgen.net/github/license/berndporr/iir1?label=LICENSE)

...maybe is a GH setup issue ?

**Comment by berndporr** [comment]
Well, this calls for good old fashioned human intervention by yourself I guess. ;)

**Comment by forart** [comment]
Thanks anyway.

**Comment by forart** [comment]
OK, I probably discovered the issue.

GH needs a license file [like this](https://github.com/apohl79/audiogridder/blob/master/COPYING) to match MIT correctly.

Hope that helps.

Thanks again for your work.
