### ISSUE TITLE
Adding lib to conan-center-index

### ISSUE THREAD

**Issue by wouterz** [berndporr/iir1#28]
Would you mind if create a recipe in order for this library to be hosted on and used in conjunction with [conan-center-index](https://github.com/conan-io/conan-center-index)?

**Comment by berndporr** [comment]
I guess you'll create a pull request? I guess it won't interfere with anything else in the library? As long as that's the case then sure, please create a recipe.

**Comment by wouterz** [comment]
No changes to this repo are needed.

I am working on the recipe, but ran into two main issues:

- GCC 5 does not seem to be supported and has been excluded in the recipe, although it should fully support c++11. ([link](https://c3i.jfrog.io/c3i/misc/summary.html?json=https://c3i.jfrog.io/c3i/misc/logs/pr/8171/2-configs/linux-gcc/iir1/1.9.0//summary.json) )
- All windows builds seem to run into a DLL loading error ([Error 3221225781](https://c3i.jfrog.io/c3i/misc/summary.html?json=https://c3i.jfrog.io/c3i/misc/logs/pr/8171/4-configs/windows-visual_studio/iir1/1.9.0//summary.json)). Any hints to what dependency might be missing?

**Comment by berndporr** [comment]
The cmake is not creating DLLs but only static libraries for windows so I guess that fails because if that? 
GCC5 fails because it doesn't like some c++11 features: iterators in the for loop. Looks like it's not 100% c++11.
