### ISSUE TITLE
Android app

### ISSUE THREAD

**Issue by hananabilabd** [berndporr/iir1#3]
Hi bro
Um working on an android app to do DSP in real-time from mic to speaker , but um using a superpowered SDK and unfortunately it doesn't allow to increase the order of filter so can i import your library in my project and replace the old filter , so Can i use your library in real-time ?? and is there an example on how to use low-pass filter and band-pass ?
Thanks in advance hhhh

**Comment by berndporr** [comment]
Just check out the readme for the example. The filter command is a realtime one. 
However, for audio JAVA will certainly be to too slow. You might need to use the C++ implementation of that library (see my github) and use JNI.

**Comment by hananabilabd** [comment]
Thanks a lot I tried using your library but I Faced a little problem that 
Realtime filtering sample by sample:
       float y = f.filter(x);

In my code i need to pass a complete array not element by element , Is there is a solution to this 
Regards

**Comment by berndporr** [comment]
So you _don't_ need realtime after all? If you have all samples then just use the Fourier Transform instead. That operates on the whole sequence. If you really want to use the IIR filter then just write a loop and send the signal through it sample by sample.

**Comment by hananabilabd** [comment]
Thanks for your answer ,I revised https://github.com/vinniefalco/DSPFilters  
the base library it says that i can pass an array 
```
f.setup (3,    // order
         44100,// sample rate
         4000, // center frequency
         880,  // band width
         1);   // ripple dB
f.process (numSamples, arrayOfChannels);
```
But when i Pass an array it comes when an error "" could not match 'type-parameter-0-0 *const' against 'float' " 
and this is due to this line of code in filter.h
`void process (int numSamples, Sample* const* arrayOfChannels)`
Do You know why is this ?

**Comment by berndporr** [comment]
I suggest you ask him.
