### ISSUE TITLE
Butterworth::HighPass<1> flips polarity of signal

### ISSUE THREAD

**Issue by heebje** [berndporr/iir1#38]
Hi,

I use a simple 6dB/oct Butterworth::HighPass<1> in an audio plugin I am developing, and I discovered that apparently it flips the polarity of the signal.
I would expect the pass band to have a phase of close to 0 degrees, but it's close to 180 degrees instead.

I noticed this when mixing the 'wet' signal of my plugin with the dry signal.
I did an extra test, outside of my plugin, just to confirm.

Is this by design?
It doesn't feel right.

**Comment by berndporr** [comment]
Can you provide a test case?
Thanks

**Comment by berndporr** [comment]
```
int main(int, char**)
{
	const int order = 1;

	// sampling rate here 1kHz as an example
	const float samplingrate = 1000;

	FILE *fimpulse = NULL;

	// Butterworth lowpass
	Iir::Butterworth::LowPass<order> f;
	double cutoff_frequency = 100; // Hz
	f.setup(samplingrate, cutoff_frequency);
	fimpulse = fopen("lp.dat", "wt");
	// let's simulated date streaming in
	for (int i = 0; i < 1000; i++)
	{
		double a = 0;
		if (i == 10) a = 1;
		double b = f.filter(a);
		fprintf(fimpulse, "%e\n", b);
	}
	fclose(fimpulse);

}
```
![i](https://user-images.githubusercontent.com/1679394/173890780-10de0ce6-53a9-413a-909a-baec5389ad9e.png)

**Comment by berndporr** [comment]
Impulse response positive so all good. Since you haven't provided a testable case I'm closing it.
