### ISSUE TITLE
Version for Arduino

### ISSUE THREAD

**Issue by propeller3D** [berndporr/iir1#60]
A DSP filter library like this seems to be some kind of hidden witchcraft, I've been looking online and this is the only library I found. I would really like to use this on an arduino. Any chance we could get a version for arduino? Thanks.

**Comment by berndporr** [comment]
It should compile no problem (without any of the demos and tests). You "just" need to figure out how to compile it.

**Comment by propeller3D** [comment]
Thanks, I will try compiling it again.
