### ISSUE TITLE
low_pass butterworth filter magnitude scaling

### ISSUE THREAD

**Issue by xhtsansiro** [berndporr/iir1#62]
In general, I wanted to filter raw force sensor data. After setting up a butterworth filter by following code 
  `  const int order = 2;
    const int numValues = 6;
    Iir::Butterworth::LowPass<order> filterButter;
    const float samplingFreq = 1000;
    const float cutoffFreq = 5; 
    filterButter.setup(samplingFreq, cutoffFreq);`
I then give the data to the filter line by line (in consectuive time order). However, what I final get is something like this pic shows, the filtered force is much higher than the original raw data. This is something that I dont expect. Have I done some mistakes? 
![xxxx](https://github.com/berndporr/iir1/assets/55890308/208002f8-40c5-4d4c-8b66-47c4f06b2268)

**Comment by berndporr** [comment]
You use a sampling rate of 1kHz, a cutoff of 5Hz and sending in 30 samples. This cannot work with just 40 samples. Sorry, but can't comment on this further. This issue tracker is about issues in the IIR filter code and not for coding help. Please go on stackoverflow for example.

Either way the gain of the filter is formalised to for the passband to one or in other words in the frequency domain.
